# Use root/example as user/password credentials
version: '3.1'

services:
  frontend:
    build: ./frontend-poly-talks
    ports:
      - "3000:3000"
    image: polytalks_frontend

  backend:
    build: ./backend-poly-talks
    ports:
      - "8080:8080"
    expose:
      - 8080
    image: polytalks_backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
